language: haskell
ghc:
  - "8.4.1"

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh

install:
  - stack setup
  - stack build --only-dependencies

script:
  - stack build
  - stack test